name: awsquiz
description: AWS Cloud Practitioner - Quiz

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  wakelock: ^0.6.2
  unity_ads_plugin: ^0.3.6
  flutter_inapp_purchase: ^5.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  rx_notifier: ^1.1.0
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true

  assets:
    - assets/images/title.png
    - assets/images/background.png

  fonts:
    - family: AWS
      fonts:
        - asset: assets/fonts/AWS-Regular.otf
